### ISSUE TITLE
需要自己開index.html嗎

### ISSUE THREAD

**Issue by yu2001-s** [ntuee-webprogramming/hack1-QAs#10]
~/Documents/wp1101/hack1/hack1$ npm start

> hack1@0.1.0 start
> react-scripts start

Could not find a required file.
  Name: index.html
  Searched in: /home/yu/Documents/wp1101/hack1/public

**Comment by chinyi0523** [comment]
不用，已經給了喔，可能是你的位置錯誤

**Comment by ntuee-webprogramming** [comment]
請確定解壓縮後檔案是加到 wp1101/hack1. 如果不是，請把所有檔案搬過來，包含 .gitignore
