### ISSUE TITLE
WSL npm start卡住

### ISSUE THREAD

**Issue by chen77526** [ntuee-webprogramming/hack1-QAs#11]
如圖，npm start完卡在這個畫面快10分鐘，請問是什麼原因呢？
![image](https://user-images.githubusercontent.com/55378273/139772993-c0689daa-4acd-4d5a-8649-037c1f3a0c7c.png)

**Comment by andyh0913** [comment]
請進入TA黃世丞的 google meet https://meet.google.com/ume-zgrb-upf

**Comment by kenchung285** [comment]
助教，我也遇到類似問題，已經要求加入google meet，名字是鍾承燁

**Comment by kenchung285** [comment]
這邊提醒大家如果也遇到可以先瀏覽器輸入 http://localhost:3000/ 試試看
