### ISSUE TITLE
yarn start 後 重新整理頁面不會顯示已save的資料

### ISSUE THREAD

**Issue by jimshao1999** [ntuee-webprogramming/hack1-QAs#13]
yarn start 後 重新整理頁面不會顯示已save的資料

**Comment by jimshao1999** [comment]
每次都要重新 yarn start 才看的到改動

**Comment by ntuee-webprogramming** [comment]
This is a frontend app. 重整後本來就不會顯示已 save 的資料

**Comment by raywu0123** [comment]
是像這樣的問題嗎?
https://stackoverflow.com/questions/43274925/development-server-of-create-react-app-does-not-auto-refresh

**Comment by ntuee-webprogramming** [comment]
解決了嗎？

**Comment by jimshao1999** [comment]
solved: added an .env file
