### ISSUE TITLE
react-script 版本問題

### ISSUE THREAD

**Issue by tinger529** [ntuee-webprogramming/hack1-QAs#14]
不知道為什麼沒有4.0.3的版本可以選(如下圖)，有辦法解決嗎? (查網路上沒看到類似的問題)
<img width="955" alt="2021-11-02 (3)" src="https://user-images.githubusercontent.com/72683977/139773575-e024e483-3b3d-4ff9-818c-35709c867c0f.png">

**Comment by raywu0123** [comment]
react-script"s"

**Comment by peterhuangfu** [comment]
套件名稱是 "react-scripts" 而非 "react-script"
建議刪掉 node_modules 後重新 yarn 或是 npm install
