### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by applelaughyo** [ntuee-webprogramming/hack1-QAs#16]
npm start 後頁面跑不出來

**Comment by kogby** [comment]
我也突然間出現了jQuery is not defined
之前都還可以

**Comment by applelaughyo** [comment]
對我也是這樣

**Comment by f06942020** [comment]
我也遇到一樣的問題，網頁會跑不出來

**Comment by chinyi0523** [comment]
https://stackoverflow.com/questions/2194992/jquery-is-not-defined
先試試看這個

**Comment by raywu0123** [comment]
可能是 vscode 自動加了 import

**Comment by applelaughyo** [comment]
請問是在那裡加

**Comment by raywu0123** [comment]
錯誤裡面應該會寫是第幾行 reference error?

**Comment by peterhuangfu** [comment]
或是可以在 code 編輯器裡面的內建搜尋看看 jQuery 是被 import 在哪邊了

**Comment by applelaughyo** [comment]
有找到jQuery
但不知道要怎麼改

**Comment by raywu0123** [comment]
那行應該是不需要的 直接刪掉就可以了

**Comment by applelaughyo** [comment]
完全不行

**Comment by applelaughyo** [comment]
刪掉後又有其他地方有

**Comment by applelaughyo** [comment]
根本刪不完

**Comment by f06942020** [comment]
我的error出現在這個檔案 ./node_modules/bootstrap/js/transition.js

+function ($) {
   ...
}(jQuery);

把jquery拿掉之後一樣有error

**Comment by ntuee-webprogramming** [comment]
真的還是不行的話，請參考：

Q1: NPM START 有問題
A1: 先試著 Google 解決，如果真的不行，就請自行重新安裝套件：

cd wp1101
rm -rf hack1
create-react-app hack1
cd hack1
yarn add bootstrap cypress seedrandom
rm -rf pubic src

後面就接著 README 把 hack1.tgz 的 code copy 過來解壓縮

**Comment by f06942020** [comment]
目前可以，感謝助教及老師回答
