### ISSUE TITLE
網頁跑不出來

### ISSUE THREAD

**Issue by AliceDu2002** [ntuee-webprogramming/hack1-QAs#17]
npm start後terminal有正常執行
但瀏覽器一直沒有出現網頁

跟平常跑不一樣的只有這裡
![image](https://user-images.githubusercontent.com/36984557/139775162-e4bd64e4-a460-485a-8aa6-699ece592c9c.png)

我有重新npm install過還是沒用

**Comment by anitalu724** [comment]
試試看把node module刪掉後再次`npm install` ，之後打個`unset HOST` 再打`npm start`看看可不可行

**Comment by ntuee-webprogramming** [comment]
解決了嗎？

**Comment by AliceDu2002** [comment]
他刪除的時候好像找不到某些檔案我就先略過
結果再npm install的時候他還是不行
我在想是不是沒清乾淨的問題
我再試一次 ~

**Comment by AliceDu2002** [comment]
還是不行嗚嗚
我應該要重新下載一個嗎

**Comment by AliceDu2002** [comment]
![image](https://user-images.githubusercontent.com/36984557/139778268-7370140b-b046-4c7c-ae8b-e2599fa105e8.png)
他可以跑到這裡 但以前就算有error他也會至少在瀏覽器跑出local 3000

**Comment by andyh0913** [comment]
請進入meet: https://meet.google.com/ume-zgrb-upf

**Comment by andyh0913** [comment]
已解決
