### ISSUE TITLE
hack1解壓縮問題

### ISSUE THREAD

**Issue by YellowJason** [ntuee-webprogramming/hack1-QAs#2]
在解壓縮hack1的時候會錯誤訊息，想請問是不是正常的

**Comment by ziv-yuan** [comment]
我也有出現

**Comment by anitalu724** [comment]
什麼樣的錯誤訊息？ 有截圖嗎？

**Comment by Eskartur** [comment]
我發在另一個issue了

**Comment by chinyi0523** [comment]
麻煩 Eskartur ziv-yuan YellowJason 進到我的meet: https://meet.google.com/gqw-cjsy-mcx

**Comment by chen77526** [comment]
我也有

**Comment by chinyi0523** [comment]
> 我也有

麻煩請到 https://meet.google.com/gqw-cjsy-mcx
