### ISSUE TITLE
Error: import { props } from 'cypress/types/bluebird'

### ISSUE THREAD

**Issue by huang3t** [ntuee-webprogramming/hack1-QAs#20]
需要把HomePage.js的import { props } from 'cypress/types/bluebird';
註解掉才能compile，不然會一直error說不能import HomePage.js裡的cypress/types/bluebird
請問會有什麼影響嗎?或是要怎麼解決?
謝謝

**Comment by chinyi0523** [comment]
原始 code 沒有 import { props } from 'cypress/types/bluebird';

**Comment by peterhuangfu** [comment]
刪掉即可

**Comment by chinyi0523** [comment]
> 需要把HomePage.js的import { props } from 'cypress/types/bluebird'; 註解掉才能compile，不然會一直error說不能import HomePage.js裡的cypress/types/bluebird 請問會有什麼影響嗎?或是要怎麼解決? 謝謝

建議看原始下載的檔案改回即可
