### ISSUE TITLE
Todo2 printBoard() 無法測試

### ISSUE THREAD

**Issue by jasperchan5** [ntuee-webprogramming/hack1-QAs#21]
在vscode中執行run code，會顯示Cannot use import statement outside a module，而問題來源是import randomNum from "./randomFixSeed";，導致無法測試printBoard()。

請問應該如何解決?

**Comment by chinyi0523** [comment]
麻煩加入meet https://meet.google.com/gqw-cjsy-mcx

**Comment by applelaughyo** [comment]
請問printborad()要打在哪裡?

**Comment by applelaughyo** [comment]
按f12之後console沒有顯示東西

**Comment by chinyi0523** [comment]
> 請問printborad()要打在哪裡?

請詳細閱讀code內容喔，不能多做提示

**Comment by anitalu724** [comment]
如果printBoard不能用(不會用)，請自己寫code測試！
*註：printBoard 這個function不在計分環節中，只是提供同學一個測試的方法，所以如果實在不能用，請自己想辦法測試，不要糾結在此function中！
