### ISSUE TITLE
無法compile

### ISSUE THREAD

**Issue by JTKiew** [ntuee-webprogramming/hack1-QAs#25]
跑出 
Failed to compile
./src/components/Board.js
Module not found: Can't resolve 'cypress/types/lodash' in '/home/jtkiew/Downloads/WebProgramming/wp1101/hack1/src/components'
This error occurred during the build time and cannot be dismissed.

後就無法compile 出網頁QAQ

**Comment by andyh0913** [comment]
請參考 #15

**Comment by chinyi0523** [comment]
please refer to #15

**Comment by JTKiew** [comment]
ok thank you
