### ISSUE TITLE
board x y的問題

### ISSUE THREAD

**Issue by Eskartur** [ntuee-webprogramming/hack1-QAs#27]
如果要用map產生row的div，需要先把board轉置，請問這個動作要在createBoard裡還是Board裡進行？

**Comment by anitalu724** [comment]
createBoard只是用來計算每個cell的value。
而你說的轉置我沒有很懂你的意思，請你把Board裡的hint和TODO3再細讀過，maybe你misunderstand了什麼。

**Comment by Eskartur** [comment]
x 是指 column index, y 是指 row index
那如果要用第一層的x來map來產生<div id='row0' style = {{display: 'flex'}}></div>的話，需要先轉置，不然會用column當成row

**Comment by anitalu724** [comment]
依照你的敘述，我覺得你還是misunderstand了什麼，請自行思考，加油！

**Comment by Eskartur** [comment]
我需要提示:(

**Comment by ntuee-webprogramming** [comment]
x 方向是 row (橫向), 所以 x 的值是 column index

**Comment by Eskartur** [comment]
x代表很多個不同的column嘛，要轉成div的話應該會變成很多不同的row

**Comment by ntuee-webprogramming** [comment]
總之，不用 transpose, 直接 map 即可
