### ISSUE TITLE
編譯問題

### ISSUE THREAD

**Issue by ryan890607** [ntuee-webprogramming/hack1-QAs#29]
助教好，我的電腦一開始跑npm start都很正常，但是剛剛突然compile fail，請問這要如何解決呢，謝謝

![image](https://user-images.githubusercontent.com/71751632/139779384-83e30f10-082f-4ae6-bb07-eab25051266c.png)

**Comment by anitalu724** [comment]
請參考 closed #15 issue

**Comment by ryan890607** [comment]
不好意思我看到有人問了，謝謝
