### ISSUE TITLE
Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by Huan80805** [ntuee-webprogramming/hack1-QAs#3]
我是用windows跑直接跑npm install的
上禮拜npm run test 還可以跑
但今天卻跑出如圖的error
![image](https://user-images.githubusercontent.com/52092671/139771105-1909493b-b579-4034-b8e7-0a35a242388e.png)
請問要怎麼解決

**Comment by raywu0123** [comment]
試試看加這個環境變數?
https://github.com/cypress-io/cypress/issues/3093

**Comment by ntuee-webprogramming** [comment]
解決了嗎？
