### ISSUE TITLE
找不到boardWrapper

### ISSUE THREAD

**Issue by Whyu1125** [ntuee-webprogramming/hack1-QAs#30]
在tes的時候 他明明找得到boardPage卻找不到boardWrapper
這應該是給定的code不知道為什麼找不到

**Comment by Whyu1125** [comment]
todo3

**Comment by chinyi0523** [comment]
請問是跑test3嗎？

**Comment by chiluen** [comment]
同樣有這個問題，error message:
AssertionError: Timed out retrying: Expected to find element: `.boardWrapper > div:nth-child(1)`, but never found it

**Comment by chinyi0523** [comment]
請看測試檔和比對自己的網頁上的Elements是否符合投影片內容

**Comment by chiluen** [comment]
並已確認boardWrapper底下已包含boardContainer，並且頁面呈現都跟pdf一樣，但是跑test3沒辦法過

**Comment by chinyi0523** [comment]
> 並已確認boardWrapper底下已包含boardContainer，並且頁面呈現都跟pdf一樣，但是跑test3沒辦法過

https://meet.google.com/gqw-cjsy-mcx

**Comment by chinyi0523** [comment]
Please check whether you delete the line in Board.js

**Comment by ntuee-webprogramming** [comment]
解決了嗎？
