### ISSUE TITLE
printBoard 一直印不出東西

### ISSUE THREAD

**Issue by YCC3741** [ntuee-webprogramming/hack1-QAs#31]
printBoard 一直印不出東西 我在 console 裡面一直看到東西被 clear 
不知道這樣的情況該如何處理

**Comment by Helena-Fu** [comment]
++ 直接一開始就printBoard但也完全沒有輸出初始值

**Comment by chinyi0523** [comment]
先不要執著這個function，往下做如果是對的就可以了

**Comment by chinyi0523** [comment]
refer to close #21
