### ISSUE TITLE
seedrandom problem

### ISSUE THREAD

**Issue by buffett0323** [ntuee-webprogramming/hack1-QAs#33]
助教我一下載下來之後的terminal無法run，因為它顯示說我util/randomFixSeed的
can't resolve seedrandom (Module not found)
我沒改過程式碼，想請問是什麼原因

**Comment by chinyi0523** [comment]
安裝包是否正確安裝？ 
如果還是不能可能要重新npm install

**Comment by ntuee-webprogramming** [comment]
@andyh0913  跟你剛剛看的是一樣的問題嗎？

**Comment by buffett0323** [comment]
您好，我重新安裝了三次，還是一樣的問題欸，而且我的npm install沒有ERROR

**Comment by raywu0123** [comment]
可以來找我 https://meet.google.com/qaa-osjf-khv
