### ISSUE TITLE
<Cell /> 預設 revealed

### ISSUE THREAD

**Issue by dadalakun** [ntuee-webprogramming/hack1-QAs#34]
<Cell /> 的預設 revealed 是 true (翻開) 的話，cypress Todo3 中的 Value Correct 這項測資會過，但是如果預設全部蓋起來則 Value Correct 會錯，想請問預設是要蓋起來還是翻開來 ?

**Comment by chinyi0523** [comment]
蓋起來

**Comment by anitalu724** [comment]
Cell.js 裡面的所有內容請**不要**更動！
