### ISSUE TITLE
我有些value設定的值就一開始給的 是亂碼

### ISSUE THREAD

**Issue by f776655321** [ntuee-webprogramming/hack1-QAs#35]
我的boaed炸彈那邊是亂碼 請問會有影響嗎

**Comment by ntuee-webprogramming** [comment]
![image](https://user-images.githubusercontent.com/72388160/139782480-9b2595d1-ac1f-4c65-a216-47dd717a8ef4.png)
是指這個嗎？

**Comment by f776655321** [comment]
對

**Comment by ntuee-webprogramming** [comment]
那應該沒關係。

**Comment by chinyi0523** [comment]
亂碼沒關係，只要網頁上可以顯示是炸彈就可以了
就複製那串亂碼當炸彈
