### ISSUE TITLE
how to submit?

### ISSUE THREAD

**Issue by JTKiew** [ntuee-webprogramming/hack1-QAs#36]
![image](https://user-images.githubusercontent.com/45333715/139782133-e3b53ccf-5e01-42cd-9ad2-fb8408715ea4.png)

**Comment by chinyi0523** [comment]
please google git merge conflict

**Comment by JTKiew** [comment]
可以提供步驟流程嗎QAQ

**Comment by raywu0123** [comment]
先 git pull 把新的東西拉下來再 push
(有很低的機率 git pull 有 conflict 造成檔案被改到, 會需要手動修)

**Comment by JTKiew** [comment]
Merge branch 'main' of https://github.com/JTKiew/wp1101 into main
# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.

gitpull 後 出現這個， ：wq 沒法使用

**Comment by chinyi0523** [comment]
https://meet.google.com/gqw-cjsy-mcx

**Comment by chinyi0523** [comment]
> Merge branch 'main' of https://github.com/JTKiew/wp1101 into main
> 
> # Please enter a commit message to explain why this merge is necessary,
> # especially if it merges an updated upstream into a topic branch.
> # Lines starting with '#' will be ignored, and an empty message aborts
> # the commit.
> gitpull 後 出現這個， ：wq 沒法使用

請加入 https://meet.google.com/gqw-cjsy-mcx
