### ISSUE TITLE
test3的value問題

### ISSUE THREAD

**Issue by chiluen** [ntuee-webprogramming/hack1-QAs#37]
在board的value設定上，我目前看printboard結果都是對的，但是在test3卻顯示 value這一項是錯的，我不太確定是不是型別設定問題(我設定過number, string 都錯)，想直接詢問助教，謝謝

**Comment by chinyi0523** [comment]
請你先確認一下test3.js上面有答案

**Comment by chiluen** [comment]
已確認答案，但還是不能過

**Comment by chinyi0523** [comment]
> 已確認答案，但還是不能過

value這一項會測試reveal和數字是否正確，請先確認Reveal是正確的

**Comment by chiluen** [comment]
因為我沒有特別動到reveal，所以都是false，這應該是正確的吧(?

**Comment by chiluen** [comment]
能請助教看一下嗎  滿疑惑的不太確定是哪裡錯誤

**Comment by chinyi0523** [comment]
> 能請助教看一下嗎 滿疑惑的不太確定是哪裡錯誤

請做完Reveal function再測試

**Comment by chinyi0523** [comment]
一開始應該全部都是蓋著的狀況

**Comment by ntuee-webprogramming** [comment]
跟這個有關嗎？

Q2: TODO 3 一直過不了？
A2: 抱歉，TODO3 的測試檔有錯誤。
TODO3 test Board.js 中的 value 有用到 Reveal 的功能，所以只寫完 TODO3 Board 沒過是正常的，需要寫完 TODO4 的 Reveal
