### ISSUE TITLE
按右鍵沒有反應

### ISSUE THREAD

**Issue by daphneeeee** [ntuee-webprogramming/hack1-QAs#38]
按左鍵跟按右鍵的時候，反應的結果是一樣的，想請問會是什麼問題呢？

**Comment by anitalu724** [comment]
可以試著在updateFlag那個function裏面用console.log 做測試

**Comment by daphneeeee** [comment]
有測試過，按左鍵跟右鍵的反應是一樣的

**Comment by anitalu724** [comment]
請進 https://meet.google.com/cvo-uyaz-zff

**Comment by ntuee-webprogramming** [comment]
@daphneeeee
