### ISSUE TITLE
Saw this while decompressing hack1.zip

### ISSUE THREAD

**Issue by Eskartur** [ntuee-webprogramming/hack1-QAs#4]
![image](https://user-images.githubusercontent.com/91512127/139771485-5e514e36-0c0b-4d76-b55b-9437901c49dc.png)

**Comment by chinyi0523** [comment]
先試看看 tgz 可不可以開

**Comment by Eskartur** [comment]
好像可以，那請問"._"的檔案要留著嗎？

**Comment by ntuee-webprogramming** [comment]
可以刪除
