### ISSUE TITLE
cypress test TODO3

### ISSUE THREAD

**Issue by vwvwMM** [ntuee-webprogramming/hack1-QAs#44]
cypress測試TODO3的時候它顯示說我的旗子數量錯了，應該要顯示10，但我人工點了好幾次(也包括重按取消旗子)，在dashboard的旗子數量都是對的，不可能是classname或id的問題吧?畢竟dashboard我們不用動，想請問這是甚麼情況?
這是我人工點的
![image](https://user-images.githubusercontent.com/71827661/139784157-8fbb11b1-bf04-4661-af74-4f1dd2410369.png)
這是cypress跑出來的錯誤:
![image](https://user-images.githubusercontent.com/71827661/139784184-71be319d-9143-4a17-9209-066caeecefd8.png)

**Comment by ntuee-webprogramming** [comment]
跟這個有關？

Q2: TODO 3 一直過不了？
A2: 抱歉，TODO3 的測試檔有錯誤。
TODO3 test Board.js 中的 value 有用到 Reveal 的功能，所以只寫完 TODO3 Board 沒過是正常的，需要寫完 TODO4 的 Reveal

**Comment by vwvwMM** [comment]
想確認一下RemainFlagNum的初始值應該是設定成0還是minesNum?我覺得我可能是RemainFlagNum的定義搞錯了

**Comment by raywu0123** [comment]
可以來找我 https://meet.google.com/qaa-osjf-khv
