### ISSUE TITLE
Modal 顯示條件

### ISSUE THREAD

**Issue by Mecoli1219** [ntuee-webprogramming/hack1-QAs#46]
是在gameOver or WIN時顯示嗎?還是本來就在那邊，但opcity＝0

**Comment by chinyi0523** [comment]
gameOver or WIN才顯示

**Comment by Mecoli1219** [comment]
不好意思，我還是不是很懂modal要放哪裡？照todo5裡說的，todo3好像會沒過

**Comment by chiluen** [comment]
一樣不知道modal要放哪QQ

**Comment by Mecoli1219** [comment]
後來決定不放了，怕第三題沒分數qq
