### ISSUE TITLE
不懂NonMinesCount作用是什麼

### ISSUE THREAD

**Issue by b06608062** [ntuee-webprogramming/hack1-QAs#47]
NonMinesCount的數量每局不是固定的嗎 ＝
boardSize^2 - mineNum
為什麼傳入revealed = (board, x, y, newNonMinesCount)會變

**Comment by raywu0123** [comment]
是成功打開的數量, 用來判斷是否遊戲結束

**Comment by chinyi0523** [comment]
每reveal後都要根據reveal 的結果做修正
