### ISSUE TITLE
無法push

### ISSUE THREAD

**Issue by ihatedeadline** [ntuee-webprogramming/hack1-QAs#49]
"fatal: Authentication failed for"
找不到push上去的方法><

**Comment by marc0620** [comment]
我的git好像找不到hack這個檔案

**Comment by andyh0913** [comment]
還是push不上去的話請進google meet: https://meet.google.com/ume-zgrb-upf

**Comment by ntuee-webprogramming** [comment]
我們會幫你重新 pull
