### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by warronyiang15** [ntuee-webprogramming/hack1-QAs#5]
<img width="1672" alt="Screenshot 2021-11-02 at 9 21 39 AM" src="https://user-images.githubusercontent.com/65525835/139771611-e90da6b0-b26d-40b0-a91d-96d872c5befc.png">

執行 npm start時出error，貌似是library的問題，請問這是正常的嗎？

**Comment by raywu0123** [comment]
可能要把 node 降到 16 版
ref: https://exerror.com/error-error0308010cdigital-envelope-routinesunsupported-in-reactjs/

**Comment by brianchung0803** [comment]
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

我將版本改成16.13.0 還是打不開

**Comment by chinyi0523** [comment]
try yarn

**Comment by down3badbad** [comment]
我也是遇到這個問題，yarn跟npm start都噴error

**Comment by brianchung0803** [comment]
我是用yarn開的

**Comment by warronyiang15** [comment]
我剛剛是將 export NODE_OPTIONS=--openssl-legacy-provider 打進去command就能跑了

**Comment by AliceDu2002** [comment]
但我打了之後他反而出現這個
--openssl-legacy-provider is not allowed in NODE_OPTIONS

**Comment by ntuee-webprogramming** [comment]
Q1: NPM START 有問題
A1: 先試著 Google 解決，如果真的不行，就請自行重新安裝套件：
> cd wp1101
> rm -rf hack1
> create-react-app hack1
> cd hack1
> yarn add bootstrap cypress seedrandom
> rm -rf pubic src
後面就接著 README 把 hack1.tgz 的 code copy 過來解壓縮

**Comment by down3badbad** [comment]
我是把版本從17.0.1下到16.13.0就可以了
