### ISSUE TITLE
請問<div className = ”modal”></div>的parent node?

### ISSUE THREAD

**Issue by joshvictor1024** [ntuee-webprogramming/hack1-QAs#50]
如題，pdf找不到qq

**Comment by anitalu724** [comment]
modal已經是這個Modal component的最上游了，自然找不到parentNode。

**Comment by joshvictor1024** [comment]
在cypress\integration\TodoTests\Todo5_Modal.js看到了，在`<div className = ”boardWrapper”></div>`底下
