### ISSUE TITLE
無法compile (Can't resolve 'seedrandom' )

### ISSUE THREAD

**Issue by b09901039** [ntuee-webprogramming/hack1-QAs#9]
./src/util/randomFixSeed.js
Module not found: Can't resolve 'seedrandom' in 'C:\Users\asus\wp1101\hack1\src\util'

npm start之後 無法compile (完全沒動其他檔案)

**Comment by raywu0123** [comment]
請問你有照 [preREADME](https://hackmd.io/3Qi1oxmkTl2uIman32U-7g?view) 的步驟先裝好 dependency 了嗎?

**Comment by chinyi0523** [comment]
麻煩請貼上error message或重新yarn /npm install

**Comment by b09901039** [comment]
yarn /npm install 出現一堆error

**Comment by b09901039** [comment]
> 麻煩請貼上error message或重新yarn /npm install

yarn /npm install 出現一堆error

**Comment by b09901039** [comment]
> 麻煩請貼上error message或重新yarn /npm install

![未命名](https://user-images.githubusercontent.com/91512287/139773620-f6404d82-a212-4b87-bddd-6f2a4fb6caf3.png)

**Comment by b09901039** [comment]
> 請問你有照 [preREADME](https://hackmd.io/3Qi1oxmkTl2uIman32U-7g?view) 的步驟先裝好 dependency 了嗎?
請問以上還有救嗎

**Comment by b09901039** [comment]
> 請問你有照 [preREADME](https://hackmd.io/3Qi1oxmkTl2uIman32U-7g?view) 的步驟先裝好 dependency 了嗎?

請問以上還有救嗎

**Comment by raywu0123** [comment]
react-script"s" typo
https://github.com/ntuee-webprogramming/hack1-QAs/issues/14

**Comment by peterhuangfu** [comment]
另外 seedrandom 可能是編輯器額外加上去的 import，去 util 裡面看有沒有多出那行 import，把它刪掉

**Comment by chinyi0523** [comment]
> 另外 seedrandom 可能是編輯器額外加上去的 import，去 util 裡面看有沒有多出那行 import，把它刪掉

這個不要刪喔，是用來fix seed的功能

**Comment by b09901039** [comment]
> react-script"s" typo #14

![未命名](https://user-images.githubusercontent.com/91512287/139774701-b3c63687-1d53-484d-bbf6-1066e6c7479c.png)
還是有error 怎麼辦

**Comment by b09901039** [comment]
> react-script"s" typo #14
是跑 npm install react-scripts 對嗎

**Comment by b09901039** [comment]
> react-script"s" typo #14

是跑 npm install react-scripts 對嗎

**Comment by chinyi0523** [comment]
> > react-script"s" typo #14
> > 是跑 npm install react-scripts 對嗎

建議直接重新install (刪除node modules)

**Comment by b09901039** [comment]
> npm install react-scripts

![image](https://user-images.githubusercontent.com/91512287/139776604-e341269d-30b6-4813-90ec-c913922367a8.png)
我全部重新了還是不行

**Comment by andyh0913** [comment]
請問你的node版本是多少呢

**Comment by ntuee-webprogramming** [comment]
如果真的還是不行...

Q1: NPM START 有問題
A1: 先試著 Google 解決，如果真的不行，就請自行重新安裝套件：

cd wp1101
rm -rf hack1
create-react-app hack1
cd hack1
yarn add bootstrap cypress seedrandom
rm -rf pubic src

後面就接著 README 把 hack1.tgz 的 code copy 過來解壓縮

**Comment by b09901039** [comment]
> 請問你的node版本是多少呢

![image](https://user-images.githubusercontent.com/91512287/139777626-1146d1cc-e0e4-4790-a928-99a421eb933e.png)
我全部打掉重安裝兩次了 又回到原點

**Comment by b09901039** [comment]
> > > react-script"s" typo #14
> > > 是跑 npm install react-scripts 對嗎
> 
> 建議直接重新install (刪除node modules)

![image](https://user-images.githubusercontent.com/91512287/139778219-6350e0e5-c3a7-4fc7-b1ab-656c26358b9f.png)
我已經全刪掉 重新安裝 完全照步驟再走 react-scripts都裝了 也有加s 還是涼去 感謝各位助教的相助

**Comment by ntuee-webprogramming** [comment]
還是涼去
是什麼意思？

**Comment by b09901039** [comment]
> 還是涼去 是什麼意思？

整個app沒辦法compiler出來

**Comment by andyh0913** [comment]
請進入 meet: https://meet.google.com/ume-zgrb-upf

**Comment by andyh0913** [comment]
已解決

**Comment by ntuee-webprogramming** [comment]
所以是什麼問題？
